using System.Globalization;
using System.Text.Json;
using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.Cloudflared;
using Aspire.Hosting.Tailscale;
using Aspire.Hosting.Tunnels;
using Microsoft.Extensions.Configuration;

namespace Aspire.Hosting;

/// <summary>
/// Aspire resource annotation holding the tap's allocated ports and the
/// list of upstream ingress entries registered via <see cref="TapExtensions.WithTap"/>.
/// </summary>
public sealed class TapIngressAnnotation : IResourceAnnotation
{
    public required int ProxyPort { get; init; }
    public required int UiPort { get; init; }
    public required string Mode { get; init; } // "standalone" | "tunnel"
    public List<TapIngressEntry> Entries { get; } = [];
}

public sealed record TapIngressEntry(
    string? Hostname,
    IResourceWithEndpoints Target,
    string? EndpointName)
{
    /// <summary>"standalone" | "existing" | "api-managed" | "dynamic" | "quick" | "tailscale-system" | "tailscale-ephemeral"</summary>
    public string? TunnelMode { get; init; }

    /// <summary>Cloudflare tunnel name (api-managed/dynamic) or null.</summary>
    public string? TunnelName { get; init; }

    /// <summary>Public URL the tunnel exposes (e.g. https://managed-tap.p7e.dev).</summary>
    public string? PublicUrl { get; init; }

    /// <summary>
    /// True when the tunnel is reachable from the public internet (Cloudflare tunnels of any
    /// kind, or Tailscale Funnel). False for tailnet-only Tailscale serve. Drives the
    /// inspector UI's public-exposure warning banner.
    /// </summary>
    public bool PublicExpose { get; init; }
}

/// <summary>
/// Handle returned by <see cref="TapExtensions.AddTap"/>; bundles the
/// underlying tap resource (project OR container) with the ingress annotation, plus
/// closures for <c>WithEnvironment</c> / <c>WithUrlForEndpoint</c> so call sites don't
/// need to know which kind of resource is hosting the tap.
/// </summary>
public sealed class TapHandle
{
    private readonly Action<Action<EnvironmentCallbackContext>> _withEnvironment;
    private readonly Action<string, Action<ResourceUrlAnnotation>> _withUrlForEndpoint;

    private TapHandle(
        IDistributedApplicationBuilder applicationBuilder,
        IResource resource,
        TapIngressAnnotation annotation,
        Action<Action<EnvironmentCallbackContext>> withEnvironment,
        Action<string, Action<ResourceUrlAnnotation>> withUrlForEndpoint)
    {
        ApplicationBuilder = applicationBuilder;
        Resource = resource;
        Annotation = annotation;
        _withEnvironment = withEnvironment;
        _withUrlForEndpoint = withUrlForEndpoint;
    }

    public IDistributedApplicationBuilder ApplicationBuilder { get; }
    public IResource Resource { get; }
    public TapIngressAnnotation Annotation { get; }
    internal TapTunnelResource? AttachedTunnel { get; set; }

    public TapHandle WithEnvironment(Action<EnvironmentCallbackContext> callback)
    {
        _withEnvironment(callback);
        return this;
    }

    public TapHandle WithEnvironment(string name, string value)
    {
        _withEnvironment(ctx => ctx.EnvironmentVariables[name] = value);
        return this;
    }

    public TapHandle WithUrlForEndpoint(string endpointName, Action<ResourceUrlAnnotation> callback)
    {
        _withUrlForEndpoint(endpointName, callback);
        return this;
    }

    internal static TapHandle ForProject(
        IDistributedApplicationBuilder applicationBuilder,
        IResourceBuilder<ProjectResource> project,
        TapIngressAnnotation annotation)
        => new(applicationBuilder, project.Resource, annotation,
            cb => project.WithEnvironment(cb),
            (name, cb) => project.WithUrlForEndpoint(name, cb));

    internal static TapHandle ForContainer(
        IDistributedApplicationBuilder applicationBuilder,
        IResourceBuilder<ContainerResource> container,
        TapIngressAnnotation annotation)
        => new(applicationBuilder, container.Resource, annotation,
            cb => container.WithEnvironment(cb),
            (name, cb) => container.WithUrlForEndpoint(name, cb));
}

public static class TapExtensions
{
    internal const int DefaultProxyPort = 5199;
    internal const int DefaultUiPort = 5198;

    /// <summary>
    /// Registers a Tap — YARP reverse proxy + capture middleware + SSE feed + bundled UI.
    /// Attach upstream services with <c>.WithTap(tap)</c>; expose them publicly with
    /// <c>tap.WithTunnel(...)</c>.
    /// </summary>
    /// <typeparam name="TTapServer">
    /// The Tap.Server project metadata generated by the consumer's AppHost
    /// (typically <c>Projects.Tap_Server</c>). Aspire's source generator only emits this
    /// type in the AppHost project, so callers must supply it here.
    /// </typeparam>
    public static TapHandle AddTap<TTapServer>(
        this IDistributedApplicationBuilder builder,
        string name = "tap",
        int proxyPort = DefaultProxyPort,
        int uiPort = DefaultUiPort,
        string mode = "standalone")
        where TTapServer : IProjectMetadata, new()
    {
        var annotation = new TapIngressAnnotation
        {
            ProxyPort = proxyPort,
            UiPort = uiPort,
            Mode = mode,
        };

        var project = builder.AddProject<TTapServer>(name)
            .WithHttpEndpoint(port: proxyPort, name: "proxy", isProxied: false)
            .WithHttpEndpoint(port: uiPort, name: "ui", isProxied: false)
            .WithAnnotation(annotation);

        var handle = TapHandle.ForProject(builder, project, annotation);
        ConfigureCommonTapEnv(handle, builder.Configuration, annotation, mode);
        return handle;
    }

    /// <summary>
    /// Same Tap, hosted as a Docker container instead of a project. The container image
    /// must contain the published <c>Tap.Server</c> with its <c>wwwroot/</c> bundled
    /// (use <c>src/backend/Tap.Server/Dockerfile</c> from this repo).
    /// </summary>
    /// <param name="exposeUiOnAllInterfaces">
    /// Publish the UI (control-plane) port on every host interface instead of loopback only.
    /// The UI branch is unauthenticated — whoever reaches it gets the whole capture ring
    /// (every proxied Authorization header and body) plus <c>DELETE /api/requests</c> and
    /// <c>POST /api/replay</c> — so opening it to the network is opt-in and belongs behind
    /// some other access control.
    /// </param>
    public static TapHandle AddTapContainer(
        this IDistributedApplicationBuilder builder,
        string name = "tap",
        string image = "ghcr.io/philbir/tap",
        string tag = "latest",
        int proxyPort = DefaultProxyPort,
        int uiPort = DefaultUiPort,
        string mode = "standalone",
        ImagePullPolicy imagePullPolicy = ImagePullPolicy.Missing,
        bool exposeUiOnAllInterfaces = false)
    {
        var annotation = new TapIngressAnnotation
        {
            ProxyPort = proxyPort,
            UiPort = uiPort,
            Mode = mode,
        };

        // Default to Missing so locally-tagged dev images (e.g. philbir/tap:local) Just Work
        // without an unintended Docker Hub pull attempt. Override with Always for floating
        // tags where you want to refresh on each AppHost run.
        var container = builder.AddContainer(name, image, tag)
            .WithImagePullPolicy(imagePullPolicy)
            .WithHttpEndpoint(port: proxyPort, targetPort: proxyPort, name: "proxy", isProxied: false)
            .WithHttpEndpoint(port: uiPort, targetPort: uiPort, name: "ui", isProxied: false)
            .WithAnnotation(annotation);

        if (!exposeUiOnAllInterfaces)
        {
            // A container port mapping binds every host interface unless it is given an explicit
            // host IP, and DCP takes that IP from the endpoint's TargetHost. Left at the default
            // this hands the whole LAN an unauthenticated control plane, where the origin guard
            // — a browser-side defence — buys nothing against curl.
            container.WithEndpoint("ui", e => e.TargetHost = "127.0.0.1", createIfNotExists: false);
        }

        var handle = TapHandle.ForContainer(builder, container, annotation);
        ConfigureCommonTapEnv(handle, builder.Configuration, annotation, mode);

        handle.WithEnvironment(ctx =>
        {
            // Inside the container both listeners must bind the wildcard address: a published
            // port arrives on the container's external interface, so a loopback-only listener
            // would refuse it. Host-side exposure is decided by the endpoint above, not here.
            ctx.EnvironmentVariables["Inspector__ProxyHost"] = "0.0.0.0";
            ctx.EnvironmentVariables["Inspector__UiHost"] = "0.0.0.0";

            if (!exposeUiOnAllInterfaces)
            {
                // Publishing on loopback still leaves DNS rebinding: a page on attacker.example
                // that resolves to 127.0.0.1 reaches the control plane and counts as same-site,
                // so the origin guard lets it through. Pinning the Host allowlist closes that,
                // and is only safe to do because we know the port isn't published any wider.
                ctx.EnvironmentVariables["Inspector__UiAllowedHosts"] = "localhost,127.0.0.1,::1";
            }
        });

        return handle;
    }

    private static void ConfigureCommonTapEnv(
        TapHandle handle,
        IConfiguration cfConfig,
        TapIngressAnnotation annotation,
        string mode)
    {
        handle
            .WithUrlForEndpoint("proxy", url => url.DisplayText = "Proxy")
            .WithUrlForEndpoint("ui", url => url.DisplayText = "Inspector UI")
            .WithEnvironment(ctx =>
            {
                ctx.EnvironmentVariables["Inspector__ProxyPort"] = annotation.ProxyPort.ToString(CultureInfo.InvariantCulture);
                ctx.EnvironmentVariables["Inspector__UiPort"] = annotation.UiPort.ToString(CultureInfo.InvariantCulture);
                ctx.EnvironmentVariables["Inspector__Mode"] = mode;
            })
            .WithEnvironment(ctx =>
            {
                var entries = annotation.Entries
                    .Select(e => new
                    {
                        hostname = e.Hostname ?? string.Empty,
                        upstream = ResolveLocalUrl(e, containerHosted: handle.Resource is ContainerResource),
                        tunnelMode = e.TunnelMode,
                        tunnelName = e.TunnelName,
                        publicUrl = e.PublicUrl,
                        publicExpose = e.PublicExpose,
                    })
                    .ToArray();
                ctx.EnvironmentVariables["Inspector__Ingress"] = JsonSerializer.Serialize(entries);
            });

        foreach (var key in new[] { "ApiToken", "AccountId", "TunnelId" })
        {
            var value = cfConfig[$"Cloudflare:{key}"];
            if (!string.IsNullOrWhiteSpace(value))
            {
                handle.WithEnvironment(ctx => ctx.EnvironmentVariables[$"Cloudflare__{key}"] = value);
            }
        }
    }

    /// <summary>
    /// Sentinel for <see cref="WithTap{T}"/>'s <c>maxRequestBodyBytes</c> default: 5 GiB.
    /// Large enough that the upstream's Kestrel won't reject practical uploads (videos,
    /// archives, large form posts), while still bounded so a runaway request can't grow
    /// without limit. Pass <c>null</c> to skip the injection entirely, or any explicit
    /// value to use that instead.
    /// </summary>
    public const long DefaultMaxRequestBodyBytes = 5L * 1024 * 1024 * 1024;

    /// <summary>
    /// Route traffic to <paramref name="builder"/>'s endpoint through the given tap.
    /// If the tap has a tunnel attached (via <see cref="CloudflaredExtensions.WithTunnel"/>
    /// or <see cref="CloudflaredExtensions.WithQuickTunnel"/>), the upstream is also published
    /// through that tunnel. <paramref name="hostname"/> is required for existing/api-managed
    /// tunnels with no dynamic-host zone.
    ///
    /// <para>
    /// By default this also injects <c>Kestrel__Limits__MaxRequestBodySize</c> into the
    /// upstream's environment so its Kestrel doesn't reject large uploads with a 413 mid-
    /// stream. Tap itself is a transparent proxy and removes its own cap; without lifting
    /// the upstream's cap too, a tunneled video upload would 413 (or hang while the client
    /// uploads the rest) at the upstream Kestrel's default 30 MB. Pass
    /// <c>maxRequestBodyBytes: null</c> to keep the upstream's own configured limit.
    /// </para>
    /// </summary>
    public static IResourceBuilder<T> WithTap<T>(
        this IResourceBuilder<T> builder,
        TapHandle tap,
        string? hostname = null,
        string? endpointName = null,
        long? maxRequestBodyBytes = DefaultMaxRequestBodyBytes)
        where T : IResourceWithEndpoints, IResourceWithEnvironment
    {
        if (maxRequestBodyBytes is { } bytes)
        {
            builder.WithEnvironment(
                "Kestrel__Limits__MaxRequestBodySize",
                bytes.ToString(CultureInfo.InvariantCulture));
        }

        switch (tap.AttachedTunnel)
        {
            case CloudflaredTunnelResource cf:
                {
                    var tunnelBuilder = tap.ApplicationBuilder.CreateResourceBuilder(cf);
                    return builder.WithCloudflareTunnel(tunnelBuilder, hostname, endpointName);
                }
            case TailscaleFunnelResource ts:
                {
                    var tunnelBuilder = tap.ApplicationBuilder.CreateResourceBuilder(ts);
                    return builder.WithTailscaleFunnel(tunnelBuilder, endpointName);
                }
            case null:
                tap.Annotation.Entries.Add(new TapIngressEntry(hostname, builder.Resource, endpointName));
                return builder;
            default:
                throw new InvalidOperationException(
                    $"Unsupported tunnel resource type '{tap.AttachedTunnel.GetType().Name}'.");
        }
    }

    internal static string ResolveLocalUrl(TapIngressEntry entry, bool containerHosted = false)
    {
        var endpoints = entry.Target.Annotations.OfType<EndpointAnnotation>().ToList();
        var endpoint = entry.EndpointName is null
            ? endpoints.FirstOrDefault(e => e.UriScheme is "http" or "https")
            : endpoints.FirstOrDefault(e => e.Name == entry.EndpointName);

        if (endpoint?.AllocatedEndpoint is null)
        {
            throw new InvalidOperationException(
                $"Cannot resolve endpoint for resource '{entry.Target.Name}'"
                + (entry.EndpointName is null ? "" : $" (endpoint '{entry.EndpointName}')")
                + ". Ensure the target resource has an HTTP endpoint.");
        }

        var host = containerHosted ? "host.docker.internal" : "localhost";
        return $"{endpoint.UriScheme}://{host}:{endpoint.AllocatedEndpoint.Port}";
    }
}
