<Project Sdk="Aspire.AppHost.Sdk/13.4.2">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>tap-sample-apphost</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tap.Hosting\Tap.Hosting.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\..\src\Tap.Server\Tap.Server.csproj" />
    <ProjectReference Include="..\Sample.Api\Sample.Api.csproj" />
    <ProjectReference Include="..\Demo.Api\Demo.Api.csproj" />
  </ItemGroup>
</Project>
