<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AspireVersion>13.2.3</AspireVersion>
    <AspNetCoreVersion>10.0.7</AspNetCoreVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.AppHost.Sdk" Version="$(AspireVersion)" />
    <PackageVersion Include="Aspire.Hosting" Version="$(AspireVersion)" />
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="$(AspireVersion)" />
    <PackageVersion Include="Aspire.Hosting.JavaScript" Version="$(AspireVersion)" />
    <PackageVersion Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>
</Project>
