using System.Globalization;
using System.Text.Json;
using Aspire.Hosting.ApplicationModel;

namespace Aspire.Hosting;

/// <summary>
/// Aspire resource annotation holding the inspector's allocated ports and the
/// list of upstream ingress entries registered via <see cref="HttpInspectorExtensions.WithInspector"/>.
/// </summary>
public sealed class HttpInspectorIngressAnnotation : IResourceAnnotation
{
    public required int ProxyPort { get; init; }
    public required int UiPort { get; init; }
    public required string Mode { get; init; } // "standalone" | "tunnel"
    public List<HttpInspectorIngressEntry> Entries { get; } = [];
}

public sealed record HttpInspectorIngressEntry(
    string? Hostname,
    IResourceWithEndpoints Target,
    string? EndpointName);

/// <summary>
/// Handle returned by <see cref="HttpInspectorExtensions.AddHttpInspector"/>; bundles the
/// underlying project resource builder with the ingress annotation so call sites can
/// attach services with <see cref="HttpInspectorExtensions.WithInspector"/>.
/// </summary>
public sealed class HttpInspectorHandle
{
    internal HttpInspectorHandle(IResourceBuilder<ProjectResource> project, HttpInspectorIngressAnnotation annotation)
    {
        Project = project;
        Annotation = annotation;
    }

    public IResourceBuilder<ProjectResource> Project { get; }
    public HttpInspectorIngressAnnotation Annotation { get; }
}

public static class HttpInspectorExtensions
{
    internal const int DefaultProxyPort = 5199;
    internal const int DefaultUiPort = 5198;

    /// <summary>
    /// Registers a stand-alone HTTP inspector — YARP reverse proxy + capture middleware + SSE feed + bundled UI.
    /// Attach upstream services with <c>.WithInspector(inspector)</c>.
    /// </summary>
    /// <typeparam name="TInspectorServer">
    /// The Tap.Server project metadata generated by the consumer's AppHost
    /// (typically <c>Projects.Tap_Server</c>). Aspire's source generator only emits this
    /// type in the AppHost project, so callers must supply it here.
    /// </typeparam>
    public static HttpInspectorHandle AddHttpInspector<TInspectorServer>(
        this IDistributedApplicationBuilder builder,
        string name = "http-inspector",
        int proxyPort = DefaultProxyPort,
        int uiPort = DefaultUiPort,
        string mode = "standalone")
        where TInspectorServer : IProjectMetadata, new()
    {
        var annotation = new HttpInspectorIngressAnnotation
        {
            ProxyPort = proxyPort,
            UiPort = uiPort,
            Mode = mode,
        };

        var project = builder.AddProject<TInspectorServer>(name)
            .WithHttpEndpoint(port: proxyPort, name: "proxy", isProxied: false)
            .WithHttpEndpoint(port: uiPort, name: "ui", isProxied: false)
            .WithEnvironment("Inspector__ProxyPort", proxyPort.ToString(CultureInfo.InvariantCulture))
            .WithEnvironment("Inspector__UiPort", uiPort.ToString(CultureInfo.InvariantCulture))
            .WithEnvironment("Inspector__Mode", mode)
            .WithEnvironment(ctx =>
            {
                var entries = annotation.Entries
                    .Select(e => new { hostname = e.Hostname ?? string.Empty, upstream = ResolveLocalUrl(e) })
                    .ToArray();
                ctx.EnvironmentVariables["Inspector__Ingress"] = JsonSerializer.Serialize(entries);
            })
            .WithAnnotation(annotation);

        // Optional Cloudflare API credentials (only meaningful for tunnel-attached mode, but
        // passing them here lets a standalone inspector reach Cloudflare too if desired).
        var cfConfig = builder.Configuration;
        foreach (var key in new[] { "ApiToken", "AccountId", "TunnelId" })
        {
            var value = cfConfig[$"Cloudflare:{key}"];
            if (!string.IsNullOrWhiteSpace(value))
            {
                project.WithEnvironment($"Cloudflare__{key}", value);
            }
        }

        return new HttpInspectorHandle(project, annotation);
    }

    /// <summary>
    /// Route traffic to <paramref name="builder"/>'s endpoint through the given inspector.
    /// If <paramref name="hostname"/> is omitted, the inspector routes any Host to this target.
    /// </summary>
    public static IResourceBuilder<T> WithInspector<T>(
        this IResourceBuilder<T> builder,
        HttpInspectorHandle inspector,
        string? hostname = null,
        string? endpointName = null)
        where T : IResourceWithEndpoints
    {
        inspector.Annotation.Entries.Add(new HttpInspectorIngressEntry(hostname, builder.Resource, endpointName));
        return builder;
    }

    internal static string ResolveLocalUrl(HttpInspectorIngressEntry entry)
    {
        var endpoints = entry.Target.Annotations.OfType<EndpointAnnotation>().ToList();
        var endpoint = entry.EndpointName is null
            ? endpoints.FirstOrDefault(e => e.UriScheme is "http" or "https")
            : endpoints.FirstOrDefault(e => e.Name == entry.EndpointName);

        if (endpoint?.AllocatedEndpoint is null)
        {
            throw new InvalidOperationException(
                $"Cannot resolve endpoint for resource '{entry.Target.Name}'"
                + (entry.EndpointName is null ? "" : $" (endpoint '{entry.EndpointName}')")
                + ". Ensure the target resource has an HTTP endpoint.");
        }

        return $"{endpoint.UriScheme}://localhost:{endpoint.AllocatedEndpoint.Port}";
    }
}
