using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using Tap.Execution.Workspace;

namespace Tap.Studio.Wsdl;

/// <summary>
/// The link between a collection and the WSDL it was generated from, stored as
/// <c>collections/&lt;slug&gt;/_wsdl.lock.json</c>.
///
/// <para>A sidecar for the same reasons <c>OpenApiLock</c> is one: the Specs emitters rebuild a
/// <c>_collection.tap</c> from a closed set of DTO fields, so an extra frontmatter key would be
/// silently deleted the first time the user saved that collection in Studio; a <c>.http</c> file
/// has no frontmatter at all; and the per-operation hashes below would bloat every git diff. The
/// loader globs only <c>*.tap</c>, <c>*.md</c> and <c>*.http</c>, so this file is invisible to
/// it.</para>
///
/// <para>Deleting it loses the recorded provenance and nothing else.</para>
/// </summary>
public sealed record WsdlLock
{
    public const string FileName = "_wsdl.lock.json";

    [JsonPropertyName("_comment")]
    public string Comment { get; init; } =
        "Generated by Tap Studio. Records the WSDL this collection came from and what was "
        + "generated for each operation. Safe to delete.";

    public int Version { get; init; } = 1;

    public required WsdlLockSource Source { get; init; }

    /// <summary><c>req</c> or <c>http</c> — which layout the requests were written in.</summary>
    public required string Layout { get; init; }

    /// <summary>Where the collection's <c>baseUrl</c> came from: <c>manual</c> when the user typed
    /// one, otherwise <c>address</c> for the origin taken off the first port.</summary>
    public string? BaseUrlSource { get; init; }

    /// <summary>Whether the generated envelopes carry a WS-Security UsernameToken header.</summary>
    public bool UsernameTokenHeader { get; init; }

    public IReadOnlyList<WsdlLockOperation> Operations { get; init; } = [];
}

public sealed record WsdlLockSource(
    /// <summary><c>url</c> | <c>file</c>.</summary>
    string Kind,
    string? Url,
    string? FileName,
    DateTimeOffset FetchedAt,
    /// <summary>Hash of the whole raw document — the cheap "did anything change at all" gate.</summary>
    string DocumentHash,
    string SpecVersion,
    string? ServiceName,
    string? TargetNamespace);

/// <summary>
/// One tracked operation. The two hashes are what a comparison needs:
/// <see cref="UpstreamHash"/> answers "did the service change?", and <see cref="GeneratedHash"/>
/// compared against what is on disk now answers "did the user edit this?".
/// </summary>
public sealed record WsdlLockOperation(
    string OpKey,
    string Service,
    string Port,
    string Name,
    string UpstreamHash,
    string GeneratedHash,
    /// <summary>The request's <c>id:</c> for <c>.req.tap</c> output — what makes tracking survive a
    /// rename or a move, since the move endpoint is a raw <c>File.Move</c> that rewrites no
    /// refs.</summary>
    string? FileId,
    /// <summary>Workspace-relative path.</summary>
    string RelativePath,
    /// <summary>The <c># @name</c> of the section, for <c>.http</c> output. Null for
    /// <c>.req.tap</c>.</summary>
    string? Fragment);

/// <summary>Reads and writes the lock. Deliberately not routed through
/// <c>WorkspaceService.Save</c>, which rejects any name <c>KindResolver</c> doesn't recognize.
/// Path safety still applies.</summary>
public sealed class WsdlLockStore(string rootDirectory)
{
    private static readonly JsonSerializerOptions Options = new()
    {
        // This file lands in the user's repo and gets read in git diffs, so it is formatted for a
        // human: indented, camelCase like every other JSON in the workspace, and with real
        // punctuation rather than \u escapes.
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        TypeInfoResolver = WsdlLockJson.Default,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    public static string PathFor(string slug) => $"collections/{slug}/{WsdlLock.FileName}";

    public WsdlLock? Read(string slug)
    {
        if (!WorkspacePaths.TryResolve(rootDirectory, PathFor(slug), out var full, out _)) return null;
        if (!File.Exists(full)) return null;
        try
        {
            return JsonSerializer.Deserialize<WsdlLock>(File.ReadAllText(full), Options);
        }
        catch (JsonException)
        {
            // A hand-mangled lock must not break the collection; the link just goes missing.
            return null;
        }
    }

    public void Write(string slug, WsdlLock lockFile)
    {
        if (!WorkspacePaths.TryResolve(rootDirectory, PathFor(slug), out var full, out var error))
            throw new InvalidOperationException(error);

        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllText(full, JsonSerializer.Serialize(lockFile, Options));
    }

    public void Delete(string slug)
    {
        if (!WorkspacePaths.TryResolve(rootDirectory, PathFor(slug), out var full, out _)) return;
        if (File.Exists(full)) File.Delete(full);
    }
}

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(WsdlLock))]
internal partial class WsdlLockJson : JsonSerializerContext;
