using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.Cloudflared;
using Aspire.Hosting.Lifecycle;
using Microsoft.Extensions.DependencyInjection;

namespace Aspire.Hosting;

public static class CloudflaredExtensions
{
    public static IResourceBuilder<CloudflaredTunnelResource> AddCloudflaredTunnel(
        this IDistributedApplicationBuilder builder,
        string name = "cloudflared")
    {
#pragma warning disable CS0618 // Eventing-based replacement is not yet wired; lifecycle hook works fine today.
        builder.Services.TryAddLifecycleHook<CloudflaredLifecycleHook>();
#pragma warning restore CS0618

        var resource = new CloudflaredTunnelResource(name, builder.Environment.ContentRootPath);

        return builder.AddResource(resource)
            .ExcludeFromManifest()
            .WithArgs(async ctx =>
            {
                ctx.Args.Add("tunnel");

                if (resource.UseLocalIngress)
                {
                    var configPath = await WriteConfigYamlAsync(resource, ctx.CancellationToken);
                    ctx.Args.Add("--config");
                    ctx.Args.Add(configPath);
                    ctx.Args.Add("run");
                    ctx.Args.Add(resource.TunnelId!);
                }
                else
                {
                    ctx.Args.Add("run");
                    ctx.Args.Add("--token");
                    ctx.Args.Add(resource.Token!);
                }
            });
    }

    public static IResourceBuilder<CloudflaredTunnelResource> WithToken(
        this IResourceBuilder<CloudflaredTunnelResource> builder,
        string? token)
    {
        if (string.IsNullOrWhiteSpace(token))
        {
            throw new ArgumentException(
                "Cloudflared tunnel token is empty. Set Cloudflare:TunnelToken via user-secrets or appsettings.",
                nameof(token));
        }

        builder.Resource.Token = token;
        builder.Resource.UseLocalIngress = false;
        return builder;
    }

    public static IResourceBuilder<CloudflaredTunnelResource> WithLocalIngress(
        this IResourceBuilder<CloudflaredTunnelResource> builder,
        string tunnelId,
        string credentialsFilePath)
    {
        builder.Resource.UseLocalIngress = true;
        builder.Resource.TunnelId = tunnelId;
        builder.Resource.CredentialsFilePath = credentialsFilePath;
        return builder;
    }

    /// <summary>
    /// Adds an HTTP inspector to the Cloudflare tunnel pipeline. Traffic flows:
    /// internet → Cloudflare → cloudflared → inspector (localhost:proxyPort) → real upstream.
    /// </summary>
    /// <typeparam name="TInspectorServer">
    /// The Tap.Server project metadata generated by the consumer's AppHost
    /// (typically <c>Projects.Tap_Server</c>).
    /// </typeparam>
    public static IResourceBuilder<CloudflaredTunnelResource> WithHttpInspector<TInspectorServer>(
        this IResourceBuilder<CloudflaredTunnelResource> builder,
        int proxyPort = HttpInspectorExtensions.DefaultProxyPort,
        int uiPort = HttpInspectorExtensions.DefaultUiPort)
        where TInspectorServer : IProjectMetadata, new()
    {
        builder.Resource.InspectorProxyPort = proxyPort;
        builder.Resource.InspectorUiPort = uiPort;

        var inspector = builder.ApplicationBuilder.AddHttpInspector<TInspectorServer>(
            name: "http-inspector",
            proxyPort: proxyPort,
            uiPort: uiPort,
            mode: "tunnel");

        builder.Resource.AttachedInspector = inspector;

        // Mirror any ingress entries that were attached to the tunnel before this call.
        foreach (var entry in builder.Resource.IngressEntries)
        {
            inspector.Annotation.Entries.Add(new HttpInspectorIngressEntry(entry.Hostname, entry.Target, entry.EndpointName));
        }

        return builder;
    }

    public static IResourceBuilder<T> WithCloudflareTunnel<T>(
        this IResourceBuilder<T> builder,
        IResourceBuilder<CloudflaredTunnelResource> tunnel,
        string hostname,
        string? endpointName = null)
        where T : IResourceWithEndpoints
    {
        tunnel.Resource.IngressEntries.Add(new CloudflaredIngressEntry(hostname, builder.Resource, endpointName));
        builder.WithAnnotation(new CloudflareTunnelAnnotation(tunnel.Resource, hostname));

        // If an inspector is attached to this tunnel, mirror the ingress so it can
        // proxy + capture the same traffic.
        if (tunnel.Resource.AttachedInspector is { } inspector)
        {
            inspector.Annotation.Entries.Add(new HttpInspectorIngressEntry(hostname, builder.Resource, endpointName));
        }

        return builder;
    }

    public static string GetCloudflareTunnelUrl<T>(this IResourceBuilder<T> builder)
        where T : IResource
    {
        if (!builder.Resource.TryGetAnnotationsOfType<CloudflareTunnelAnnotation>(out var annotations))
        {
            throw new InvalidOperationException(
                $"Resource '{builder.Resource.Name}' has no Cloudflare tunnel attached. Call .WithCloudflareTunnel(...) first.");
        }

        return annotations.First().PublicUrl;
    }

    private static async Task<string> WriteConfigYamlAsync(
        CloudflaredTunnelResource tunnel,
        CancellationToken cancellationToken)
    {
        var path = Path.Combine(Path.GetTempPath(), $"cloudflared-{tunnel.Name}-{Guid.NewGuid():N}.yml");
        var lines = new List<string>
        {
            $"tunnel: {tunnel.TunnelId}",
            $"credentials-file: {tunnel.CredentialsFilePath}",
            "ingress:",
        };

        foreach (var entry in tunnel.IngressEntries)
        {
            // If an inspector is attached, route ALL ingress through it so traffic is captured.
            // The inspector then resolves hostname -> real upstream via its own ingress config.
            var service = tunnel.InspectorProxyPort.HasValue
                ? $"http://localhost:{tunnel.InspectorProxyPort.Value}"
                : ResolveLocalUrl(entry);

            lines.Add($"  - hostname: {entry.Hostname}");
            lines.Add($"    service: {service}");
        }

        lines.Add("  - service: http_status:404");

        await File.WriteAllLinesAsync(path, lines, cancellationToken);
        return path;
    }

    private static string ResolveLocalUrl(CloudflaredIngressEntry entry) =>
        HttpInspectorExtensions.ResolveLocalUrl(new HttpInspectorIngressEntry(entry.Hostname, entry.Target, entry.EndpointName));
}
