using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using Tap.Execution.Workspace;

namespace Tap.Studio.OpenApi;

/// <summary>
/// The link between a collection and the OpenAPI document it was generated from, stored as
/// <c>collections/&lt;slug&gt;/_openapi.lock.json</c>.
///
/// <para><b>Why a sidecar and not frontmatter.</b> The Specs emitters rebuild a
/// <c>_collection.tap</c> from a closed set of DTO fields, so any extra key would be silently
/// deleted the first time the user saved that collection in Studio. A <c>.http</c> file has no
/// frontmatter at all. And the per-operation hashes below would bloat every git diff. The loader
/// globs only <c>*.tap</c>, <c>*.md</c> and <c>*.http</c>, so this file is invisible to it — one
/// file, never a directory, or it would show up as an empty node in the explorer.</para>
///
/// <para>Deleting it loses re-sync and nothing else.</para>
/// </summary>
public sealed record OpenApiLock
{
    public const string FileName = "_openapi.lock.json";

    [JsonPropertyName("_comment")]
    public string Comment { get; init; } =
        "Generated by Tap Studio. Links this collection to the OpenAPI document it came from so "
        + "re-sync can tell upstream changes from your edits. Safe to delete — you lose re-sync.";

    public int Version { get; init; } = 1;

    public required OpenApiLockSource Source { get; init; }

    /// <summary><c>req</c> or <c>http</c> — re-sync has to regenerate in the same shape.</summary>
    public required string Layout { get; init; }

    /// <summary>
    /// Where the collection's <c>baseUrl</c> came from. <c>aspire</c> means it is a
    /// <c>{{aspire:name}}</c> template that must survive re-sync untouched — surviving reallocated
    /// ports is the entire point of that provider, and <c>servers[0]</c> would clobber it.
    /// </summary>
    public string? BaseUrlSource { get; init; }

    public IReadOnlyList<OpenApiLockOperation> Operations { get; init; } = [];
}

public sealed record OpenApiLockSource(
    /// <summary><c>url</c> | <c>file</c> | <c>aspire</c>.</summary>
    string Kind,
    string? Url,
    string? FileName,
    DateTimeOffset FetchedAt,
    /// <summary>Hash of the whole raw document — the cheap "did anything change at all" gate.</summary>
    string DocumentHash,
    string SpecVersion,
    string? ApiVersion);

/// <summary>
/// One tracked operation. The two hashes are the whole trick: <see cref="UpstreamHash"/> answers
/// "did the API change?", and <see cref="GeneratedHash"/> compared against what is on disk now
/// answers "did the user edit this?". Only when both moved is there a conflict.
/// </summary>
public sealed record OpenApiLockOperation(
    string OpKey,
    string? OperationId,
    string Method,
    string Path,
    string UpstreamHash,
    string GeneratedHash,
    /// <summary>The request's <c>id:</c> for <c>.req.tap</c> output. This is what makes tracking
    /// survive a rename or a move — the move endpoint is a raw <c>File.Move</c> that rewrites no
    /// refs, so a path-keyed lock would break on the first drag in the explorer.</summary>
    string? FileId,
    /// <summary>Workspace-relative path, repaired on each write when the file has moved.</summary>
    string RelativePath,
    /// <summary>The <c># @name</c> of the section, for <c>.http</c> output. Null for
    /// <c>.req.tap</c>.</summary>
    string? Fragment);

/// <summary>Reads and writes the lock. Deliberately not routed through
/// <c>WorkspaceService.Save</c>, which rejects any name <c>KindResolver</c> doesn't recognize —
/// the same reason <c>FileEndpoints</c> writes uploads directly. Path safety still applies.</summary>
public sealed class OpenApiLockStore(string rootDirectory)
{
    private static readonly JsonSerializerOptions Options = new()
    {
        // This file lands in the user's repo and gets read in git diffs, so it is formatted for a
        // human: indented, camelCase like every other JSON in the workspace, and with real
        // punctuation rather than — escapes. The naming policy is set here as well as on the
        // context because supplying a resolver to a fresh options object does not carry it over.
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        TypeInfoResolver = OpenApiLockJson.Default,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    public static string PathFor(string slug) => $"collections/{slug}/{OpenApiLock.FileName}";

    public OpenApiLock? Read(string slug)
    {
        if (!WorkspacePaths.TryResolve(rootDirectory, PathFor(slug), out var full, out _)) return null;
        if (!File.Exists(full)) return null;
        try
        {
            return JsonSerializer.Deserialize<OpenApiLock>(File.ReadAllText(full), Options);
        }
        catch (JsonException)
        {
            // A hand-mangled lock must not break the collection; re-sync just goes unavailable.
            return null;
        }
    }

    public void Write(string slug, OpenApiLock lockFile)
    {
        if (!WorkspacePaths.TryResolve(rootDirectory, PathFor(slug), out var full, out var error))
            throw new InvalidOperationException(error);

        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllText(full, JsonSerializer.Serialize(lockFile, Options));
    }

    public void Delete(string slug)
    {
        if (!WorkspacePaths.TryResolve(rootDirectory, PathFor(slug), out var full, out _)) return;
        if (File.Exists(full)) File.Delete(full);
    }
}

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(OpenApiLock))]
internal partial class OpenApiLockJson : JsonSerializerContext;
